access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://veenaththamuditha:SrKdlIXz6N9OCiPs@socialapp.xkcgo6l.mongodb.net/foodiesdb?retryWrites=true&w=majority&appName=SocialAPP
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081